[package]
name = "axcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
libc = "0.2.154"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
env_logger = "0.11.3"
log = "0.4.21"
goblin = "0.10.0"
lazyinit = "0.2"
axerrno = "0.1.0"
sc = "0.2.7"

memory_addr = "0.3"
page_table_multiarch = "0.5"
axhvc = { git = "https://github.com/arceos-hypervisor/axhvc.git" }
axvmconfig = { git = "https://github.com/arceos-hypervisor/axvmconfig.git", default-features = false }

[patch."https://github.com/arceos-hypervisor/axhvc.git"]
axhvc = { path = "../../../crates/axhvc" }

[patch.crates-io]
memory_addr = { path = "../../../crates/memory_addr/memory_addr" }
page_table_multiarch = { path = "../../../crates/page_table_multiarch/page_table_multiarch" }

[build-dependencies]
bindgen = "0.72"
