[package]
name = "axcli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
libc = "0.2.154"
serde = { version = "1.0.204", features = ["derive"] }
toml = "0.8.14"
env_logger = "0.11.3"
log = "0.4.21"
goblin = "0.10.0"
lazyinit = "0.2"
axerrno = "0.1.0"
sc = "0.2.7"

axhvc = { git = "https://github.com/arceos-hypervisor/axhvc.git", branch = "create_vm" }
axvmconfig = { git = "https://github.com/arceos-hypervisor/axvmconfig.git", default-features = false }
